// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: proto/tax.proto

package productCatalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateTaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineItems       []*ProductLineItem `protobuf:"bytes,1,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	CustomerDetails *CustomerDetails   `protobuf:"bytes,2,opt,name=customer_details,json=customerDetails,proto3" json:"customer_details,omitempty"`
	ShippingFee     float64            `protobuf:"fixed64,3,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
}

func (x *CalculateTaxRequest) Reset() {
	*x = CalculateTaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateTaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTaxRequest) ProtoMessage() {}

func (x *CalculateTaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTaxRequest.ProtoReflect.Descriptor instead.
func (*CalculateTaxRequest) Descriptor() ([]byte, []int) {
	return file_proto_tax_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateTaxRequest) GetLineItems() []*ProductLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *CalculateTaxRequest) GetCustomerDetails() *CustomerDetails {
	if x != nil {
		return x.CustomerDetails
	}
	return nil
}

func (x *CalculateTaxRequest) GetShippingFee() float64 {
	if x != nil {
		return x.ShippingFee
	}
	return 0
}

type CalculateTaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AmountTotal float64 `protobuf:"fixed64,2,opt,name=amount_total,json=amountTotal,proto3" json:"amount_total,omitempty"`
	TaxAmount   float64 `protobuf:"fixed64,3,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
}

func (x *CalculateTaxResponse) Reset() {
	*x = CalculateTaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateTaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTaxResponse) ProtoMessage() {}

func (x *CalculateTaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTaxResponse.ProtoReflect.Descriptor instead.
func (*CalculateTaxResponse) Descriptor() ([]byte, []int) {
	return file_proto_tax_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateTaxResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalculateTaxResponse) GetAmountTotal() float64 {
	if x != nil {
		return x.AmountTotal
	}
	return 0
}

func (x *CalculateTaxResponse) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

type ProductLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount      float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Quantity    int64   `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reference   string  `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	TaxCode     string  `protobuf:"bytes,4,opt,name=tax_code,json=taxCode,proto3" json:"tax_code,omitempty"`
	TaxBehavior string  `protobuf:"bytes,5,opt,name=tax_behavior,json=taxBehavior,proto3" json:"tax_behavior,omitempty"`
}

func (x *ProductLineItem) Reset() {
	*x = ProductLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductLineItem) ProtoMessage() {}

func (x *ProductLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductLineItem.ProtoReflect.Descriptor instead.
func (*ProductLineItem) Descriptor() ([]byte, []int) {
	return file_proto_tax_proto_rawDescGZIP(), []int{2}
}

func (x *ProductLineItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProductLineItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductLineItem) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ProductLineItem) GetTaxCode() string {
	if x != nil {
		return x.TaxCode
	}
	return ""
}

func (x *ProductLineItem) GetTaxBehavior() string {
	if x != nil {
		return x.TaxBehavior
	}
	return ""
}

type CustomerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country     string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	State       string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode  string `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	AddressType string `protobuf:"bytes,4,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	City        string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Line1       string `protobuf:"bytes,6,opt,name=line1,proto3" json:"line1,omitempty"`
}

func (x *CustomerDetails) Reset() {
	*x = CustomerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tax_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerDetails) ProtoMessage() {}

func (x *CustomerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tax_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerDetails.ProtoReflect.Descriptor instead.
func (*CustomerDetails) Descriptor() ([]byte, []int) {
	return file_proto_tax_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerDetails) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CustomerDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CustomerDetails) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CustomerDetails) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *CustomerDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CustomerDetails) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

var File_proto_tax_proto protoreflect.FileDescriptor

var file_proto_tax_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x22, 0xc4, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09,
	0x6c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x4a, 0x0a, 0x10, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x73, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x22, 0x68, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x78, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x78, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x78, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x78, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x78, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x31, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tax_proto_rawDescOnce sync.Once
	file_proto_tax_proto_rawDescData = file_proto_tax_proto_rawDesc
)

func file_proto_tax_proto_rawDescGZIP() []byte {
	file_proto_tax_proto_rawDescOnce.Do(func() {
		file_proto_tax_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tax_proto_rawDescData)
	})
	return file_proto_tax_proto_rawDescData
}

var file_proto_tax_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tax_proto_goTypes = []interface{}{
	(*CalculateTaxRequest)(nil),  // 0: productCatalog.CalculateTaxRequest
	(*CalculateTaxResponse)(nil), // 1: productCatalog.CalculateTaxResponse
	(*ProductLineItem)(nil),      // 2: productCatalog.ProductLineItem
	(*CustomerDetails)(nil),      // 3: productCatalog.CustomerDetails
}
var file_proto_tax_proto_depIdxs = []int32{
	2, // 0: productCatalog.CalculateTaxRequest.line_items:type_name -> productCatalog.ProductLineItem
	3, // 1: productCatalog.CalculateTaxRequest.customer_details:type_name -> productCatalog.CustomerDetails
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tax_proto_init() }
func file_proto_tax_proto_init() {
	if File_proto_tax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateTaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateTaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tax_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tax_proto_goTypes,
		DependencyIndexes: file_proto_tax_proto_depIdxs,
		MessageInfos:      file_proto_tax_proto_msgTypes,
	}.Build()
	File_proto_tax_proto = out.File
	file_proto_tax_proto_rawDesc = nil
	file_proto_tax_proto_goTypes = nil
	file_proto_tax_proto_depIdxs = nil
}
