// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"productCatalog/ent/merchandise"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MerchandiseCreate is the builder for creating a Merchandise entity.
type MerchandiseCreate struct {
	config
	mutation *MerchandiseMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (mc *MerchandiseCreate) SetType(m merchandise.Type) *MerchandiseCreate {
	mc.mutation.SetType(m)
	return mc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableType(m *merchandise.Type) *MerchandiseCreate {
	if m != nil {
		mc.SetType(*m)
	}
	return mc
}

// SetTypeID sets the "type_id" field.
func (mc *MerchandiseCreate) SetTypeID(s string) *MerchandiseCreate {
	mc.mutation.SetTypeID(s)
	return mc
}

// SetNillableTypeID sets the "type_id" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableTypeID(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetTypeID(*s)
	}
	return mc
}

// SetStock sets the "stock" field.
func (mc *MerchandiseCreate) SetStock(i int) *MerchandiseCreate {
	mc.mutation.SetStock(i)
	return mc
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableStock(i *int) *MerchandiseCreate {
	if i != nil {
		mc.SetStock(*i)
	}
	return mc
}

// SetPendingPeriod sets the "pending_period" field.
func (mc *MerchandiseCreate) SetPendingPeriod(i int) *MerchandiseCreate {
	mc.mutation.SetPendingPeriod(i)
	return mc
}

// SetNillablePendingPeriod sets the "pending_period" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillablePendingPeriod(i *int) *MerchandiseCreate {
	if i != nil {
		mc.SetPendingPeriod(*i)
	}
	return mc
}

// SetName sets the "name" field.
func (mc *MerchandiseCreate) SetName(s string) *MerchandiseCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableName(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetName(*s)
	}
	return mc
}

// SetDisplayName sets the "display_name" field.
func (mc *MerchandiseCreate) SetDisplayName(s string) *MerchandiseCreate {
	mc.mutation.SetDisplayName(s)
	return mc
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDisplayName(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetDisplayName(*s)
	}
	return mc
}

// SetPictureURL sets the "picture_url" field.
func (mc *MerchandiseCreate) SetPictureURL(s string) *MerchandiseCreate {
	mc.mutation.SetPictureURL(s)
	return mc
}

// SetNillablePictureURL sets the "picture_url" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillablePictureURL(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetPictureURL(*s)
	}
	return mc
}

// SetDescription sets the "description" field.
func (mc *MerchandiseCreate) SetDescription(s string) *MerchandiseCreate {
	mc.mutation.SetDescription(s)
	return mc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDescription(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetDescription(*s)
	}
	return mc
}

// SetPrice sets the "price" field.
func (mc *MerchandiseCreate) SetPrice(f float64) *MerchandiseCreate {
	mc.mutation.SetPrice(f)
	return mc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillablePrice(f *float64) *MerchandiseCreate {
	if f != nil {
		mc.SetPrice(*f)
	}
	return mc
}

// SetRefundableRatio sets the "refundable_ratio" field.
func (mc *MerchandiseCreate) SetRefundableRatio(f float64) *MerchandiseCreate {
	mc.mutation.SetRefundableRatio(f)
	return mc
}

// SetNillableRefundableRatio sets the "refundable_ratio" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableRefundableRatio(f *float64) *MerchandiseCreate {
	if f != nil {
		mc.SetRefundableRatio(*f)
	}
	return mc
}

// SetDeductionRatio sets the "deduction_ratio" field.
func (mc *MerchandiseCreate) SetDeductionRatio(f float64) *MerchandiseCreate {
	mc.mutation.SetDeductionRatio(f)
	return mc
}

// SetNillableDeductionRatio sets the "deduction_ratio" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDeductionRatio(f *float64) *MerchandiseCreate {
	if f != nil {
		mc.SetDeductionRatio(*f)
	}
	return mc
}

// SetDeductionReason sets the "deduction_reason" field.
func (mc *MerchandiseCreate) SetDeductionReason(s string) *MerchandiseCreate {
	mc.mutation.SetDeductionReason(s)
	return mc
}

// SetNillableDeductionReason sets the "deduction_reason" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDeductionReason(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetDeductionReason(*s)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MerchandiseCreate) SetCreatedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableCreatedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MerchandiseCreate) SetUpdatedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableUpdatedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetUpdatedAt(*t)
	}
	return mc
}

// SetDeletedAt sets the "deleted_at" field.
func (mc *MerchandiseCreate) SetDeletedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetDeletedAt(t)
	return mc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDeletedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetDeletedAt(*t)
	}
	return mc
}

// Mutation returns the MerchandiseMutation object of the builder.
func (mc *MerchandiseCreate) Mutation() *MerchandiseMutation {
	return mc.mutation
}

// Save creates the Merchandise in the database.
func (mc *MerchandiseCreate) Save(ctx context.Context) (*Merchandise, error) {
	var (
		err  error
		node *Merchandise
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MerchandiseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			if node, err = mc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			if mc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MerchandiseCreate) SaveX(ctx context.Context) *Merchandise {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MerchandiseCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MerchandiseCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MerchandiseCreate) defaults() {
	if _, ok := mc.mutation.GetType(); !ok {
		v := merchandise.DefaultType
		mc.mutation.SetType(v)
	}
	if _, ok := mc.mutation.Stock(); !ok {
		v := merchandise.DefaultStock
		mc.mutation.SetStock(v)
	}
	if _, ok := mc.mutation.PendingPeriod(); !ok {
		v := merchandise.DefaultPendingPeriod
		mc.mutation.SetPendingPeriod(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := merchandise.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		v := merchandise.DefaultUpdatedAt()
		mc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MerchandiseCreate) check() error {
	if _, ok := mc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Merchandise.type"`)}
	}
	if v, ok := mc.mutation.GetType(); ok {
		if err := merchandise.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Merchandise.type": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "Merchandise.stock"`)}
	}
	if _, ok := mc.mutation.PendingPeriod(); !ok {
		return &ValidationError{Name: "pending_period", err: errors.New(`ent: missing required field "Merchandise.pending_period"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Merchandise.created_at"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Merchandise.updated_at"`)}
	}
	return nil
}

func (mc *MerchandiseCreate) sqlSave(ctx context.Context) (*Merchandise, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MerchandiseCreate) createSpec() (*Merchandise, *sqlgraph.CreateSpec) {
	var (
		_node = &Merchandise{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: merchandise.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: merchandise.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: merchandise.FieldType,
		})
		_node.Type = value
	}
	if value, ok := mc.mutation.TypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldTypeID,
		})
		_node.TypeID = value
	}
	if value, ok := mc.mutation.Stock(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: merchandise.FieldStock,
		})
		_node.Stock = value
	}
	if value, ok := mc.mutation.PendingPeriod(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: merchandise.FieldPendingPeriod,
		})
		_node.PendingPeriod = value
	}
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mc.mutation.DisplayName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldDisplayName,
		})
		_node.DisplayName = value
	}
	if value, ok := mc.mutation.PictureURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldPictureURL,
		})
		_node.PictureURL = value
	}
	if value, ok := mc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := mc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: merchandise.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := mc.mutation.RefundableRatio(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: merchandise.FieldRefundableRatio,
		})
		_node.RefundableRatio = value
	}
	if value, ok := mc.mutation.DeductionRatio(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: merchandise.FieldDeductionRatio,
		})
		_node.DeductionRatio = value
	}
	if value, ok := mc.mutation.DeductionReason(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldDeductionReason,
		})
		_node.DeductionReason = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := mc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// MerchandiseCreateBulk is the builder for creating many Merchandise entities in bulk.
type MerchandiseCreateBulk struct {
	config
	builders []*MerchandiseCreate
}

// Save creates the Merchandise entities in the database.
func (mcb *MerchandiseCreateBulk) Save(ctx context.Context) ([]*Merchandise, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Merchandise, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchandiseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MerchandiseCreateBulk) SaveX(ctx context.Context) []*Merchandise {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MerchandiseCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MerchandiseCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
